### ISSUE TITLE
Riotee Big - a second generation module capable of running Linux (32-64MB RAM) and with at least 2 microphone inputs

### ISSUE THREAD

**Issue by dumblob** [NessieCircuits/Riotee_Board#1]
I noticed the campaign on Crowdsupply and it looks great. Congratulations!

For my use cases I would need to run Linux on the Cortex (or maybe a slightly faster Cortex, but not necessarily) and would need to have the possibility to connect 2 separate mono microphones.

Do you have such plans for the future?

My use case would be to make a custom board and/or shield with a battery pack, SD card (for Linux + storage), 2 mic pinouts (mics themself would not be on board) and an LTE chip. All that in a smallest possible package :wink:.

**Comment by geissdoerfer** [comment]
Hi, thanks! Your project sounds interesting. However our focus is on battery-free devices. Running Linux requires a more capable SoC and would be a great challenge without a continuous power supply. I'm not aware of any research in that direction.

For your particular project I would probably look into something like a Raspberry Pi or Beaglebone. They run Linux out of the box and you can power them from batteries.

**Comment by dumblob** [comment]
Thanks for the quick reply!

Yeah, all other platforms I know about are really huge. I envision/need it of less than 70% of the size of a raspi pico (not counting the battery).
